### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by suxianl** [SCAN-NRAD/DL-DiReCT#5]
Hello, I'm trying to run DL-DiReCT on a workstation ,actually i ano sure whether it was installed well.
and the program prompted that as follow,and i want to know how to eliminate this question,Thanks in advance.  :

(DL) C:\Users\SU>dl+direct -h
Traceback (most recent call last):
  File "\\?\S:\SU\anaconda\envs\DL\Scripts\dl+direct-script.py", line 33, in <module>
    sys.exit(load_entry_point('DL-DiReCT==1.0.0', 'console_scripts', 'dl+direct')())
  File "\\?\S:\SU\anaconda\envs\DL\Scripts\dl+direct-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "S:\SU\anaconda\envs\DL\lib\importlib\metadata\__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "S:\SU\anaconda\envs\DL\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'run_script'

**Comment by mrunibe** [comment]
Hi,

It looks like the source directory might no longer be available. After you put the source in a directory (either with git clone or by extracting the zip: https://github.com/SCAN-NRAD/DL-DiReCT/archive/refs/heads/main.zip), did you run '**pip install -e .**' within that directory?
You still need to keep that directory after the installation. Is that directory still present? Ensure that the package is installed with the '**-e**' option.

It also looks like you are running it under windows. Although DL+DiReCT should in principle run under windows, it requires a linux shell. You might want to use Windows WSL for this (https://learn.microsoft.com/en-us/windows/wsl/install).
